events/urls.py
from django.conf.urls import url

from . import views
from . import email_template_views
from . import job_posting_views

app_name = 'events'

urlpatterns = [
    url(r'^(?P<event_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^edit/(?P<event_id>[0-9]+)?/?$', views.edit, name='edit'),
    url(r'^templates/edit/(?P<template_id>[0-9]+)?/?$', email_template_views.edit, name='edit_email_template'),
    url(r'^templates$', email_template_views.index, name='email_template_index'),
    url(r'^postings/edit/(?P<job_posting_id>[0-9]+)?/?$', job_posting_views.edit, name='job_posting_template'),
    url(r'^postings$', job_posting_views.index, name='job_posting_template'),
    url(r'^$', views.index, name='index'),
]

events/models/attendance.py
from __future__ import unicode_literals
from django.db import models

from events.models.candidate import Candidate
from events.models.event import Event
from events.models.job_posting import JobPosting
from django.db import connection

class Attendance(models.Model):
    candidate = models.ForeignKey(Candidate)
    event = models.ForeignKey(Event)
    selected_job_posting = models.ForeignKey(JobPosting)

    def __str__(self):
        return "{0} : {1} was attended by {2} : {3}".format(self.event.id, self.event, self.candidate, self.selected_job_posting)

    def candidates_for_event(event):
        sql = """
            SELECT can.first_name as first_name, can.last_name, can.phone, can.email, string_agg(jp.title, ', ')
            FROM public.events_attendance att
            JOIN public.events_candidate can on can.id = att.candidate_id
            JOIN public.events_event evt on evt.id = att.event_id
            JOIN public.events_jobposting jp on jp.id = att.selected_job_posting_id
            WHERE evt.id = """ + event + """
            GROUP BY can.id
            """
        cursor = connection.cursor()
        cursor.execute(sql)
        return [ EventCandidate(val) for val in cursor.fetchall()]

    class Meta:
        ordering = ['event']

class EventCandidate:
    def __init__(self, list):
        self.first_name = list[0]
        self.last_name = list[1]
        self.phone = list[2]
        self.email = list[3]
        self.postings = list[4]
        self.email_error = False
        

events/models/candidate.py
from __future__ import unicode_literals
from django.core.validators import RegexValidator
from django.db import models

from events.models.job_posting import JobPosting


class Candidate(models.Model):
    first_name = models.CharField('First Name', max_length=200)
    last_name = models.CharField('Last Name', max_length=200)
    email = models.EmailField(max_length=200)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{8,15}$',
                                 message='Phone number must be entered in the format: ''+999999999''. Up to 15 digits allowed.')
    phone = models.CharField(validators=[phone_regex], blank=True,
                             max_length=16, null=True) #validators should be a list
    selected_jobs = models.ManyToManyField(JobPosting, through='Attendance')

    def __str__(self):
        return "{0} {1} - {2}".format(self.first_name, self.last_name, self.email)

    # These permit use as a dictionary key
    def __hash__(self):
        return hash(self.id)

    def __eq__(self, other):
        return other and self.id == other.id

    def __ne__(self, other):
        return not(self == other)

    class Meta:
        verbose_name_plural = 'Candidates'

events/models/event.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError

from events.models.job_posting import JobPosting
from sendemail.models.email_template import EmailTemplate


class Event(models.Model):
    title = models.TextField(blank=False)
    date_time = models.DateField('Event date', default=timezone.now)
    enabled = models.BooleanField(default=True)
    job_postings = models.ManyToManyField(JobPosting, blank=True,
                                          help_text='Select all Job Postings being recruited for this Event.')
    auto_email = models.BooleanField('Auto send email on registration', default=False)
    auto_email_from = models.EmailField('Auto send from email',
                                        max_length=200, blank=True, null=True)
    email_template = models.ForeignKey(EmailTemplate, blank=True, null=True,
                                       help_text='Select the email template for auto-sending emails at this event.')

    def __str__(self):
        return self.title

    def clean(self):
        if self.auto_email:
            if not self.auto_email_from:
                raise ValidationError({'auto_email_from': ('Auto Email must have corresponding sender defined.')})
            if not self.email_template:
                raise ValidationError({'email_template': ('Auto Email must have corresponding template defined.')})

        return super(Event, self)

    class Meta:
        ordering = ['-date_time']

events/models/job_posting.py
from __future__ import unicode_literals
from django.db import models
from django.utils.html import format_html


class JobPosting(models.Model):
    title = models.CharField(max_length=300)
    location = models.CharField(max_length=100, blank=True, null=True)
    job_link = models.URLField('Job Link', max_length=500)
    enabled = models.BooleanField(default=True)

    def show_job_url(self, obj):
        return format_html("<a href='{url}'>{url}</a>", url=obj.job_link)

    show_job_url.short_description = "Job URL"

    def __str__(self):
        if self.location is None or self.location == '':
            return self.title
        else:
            return "{0} ({1})".format(self.title, self.location)

events/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import inlineformset_factory

from events.models.attendance import Attendance
from events.models.job_posting import JobPosting

from sendemail.models.email_template import EmailTemplate

class RegisterForm(forms.Form):
    candidate_first_name = forms.CharField(label='First name:', max_length=50)
    candidate_last_name = forms.CharField(label='Last name:', max_length=50)
    candidate_email = forms.EmailField(label='Email:', max_length=200)
    phone_regex = RegexValidator(regex=r'^\d{3}-\d{3}-\d{4}$',
                                 message='Phone number must be entered in the format: \'123-123-1234\'.')
    candidate_phone = forms.CharField(validators=[phone_regex], label='Phone number:', max_length=12, required=False, widget=forms.TextInput(attrs={'placeholder': 'XXX-XXX-XXXX'}))
    JobPostingFormSet = inlineformset_factory(JobPosting, Attendance, fields=('selected_job_posting',))
    candidate_job_postings = forms.MultipleChoiceField(label='Jobs:', initial='', widget=forms.SelectMultiple(), required=True)

class EventForm(forms.Form):
    event_date = forms.DateField(label='Event date', widget=forms.TextInput(attrs={'autocomplete':'off'}))
    event_title = forms.CharField(label='Title of Event')
    event_jobs = forms.MultipleChoiceField(label='Job postings', initial='', widget=forms.SelectMultiple(), required=True)
    event_auto_send = forms.BooleanField(label='Auto send email on registration', required=False)
    event_sender = forms.EmailField(label='Auto-email sender', max_length=200, required=False)
    event_default_template = forms.ChoiceField(label='Default email template', initial='', required=False)

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        self.fields['event_default_template'].choices = [('','')] + [(email_template.id, str(email_template)) for email_template in EmailTemplate.objects.filter(enabled=True)]

        self.fields['event_jobs'].choices = [(job_posting.id, str(job_posting)) for job_posting in JobPosting.objects.filter(enabled=True)]

events/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse

from events.models.attendance import Attendance
from events.models.candidate import Candidate
from events.models.event import Event
from events.models.job_posting import JobPosting
from sendemail.models.email_template import EmailTemplate

from sendemail.views import send_emails
from .forms import RegisterForm, EventForm

import json
from django.core.validators import validate_email


def index(request):
    event_list = Event.objects.filter(enabled=True).order_by('-date_time')
    context = {'event_list': event_list, 'has_events': len(event_list) > 0 }
    return render(request, 'events/index.html', context)


def detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)

    if request.method == 'POST':  # if this is a POST request we need to process the form data
        form = RegisterForm(request.POST)
        form.fields['candidate_job_postings'].choices = get_job_postings_for_event(event_id)
        if form.is_valid():
            candidate_email = update_or_create_candidate(request, form, event_id)
            context = {'candidate_email': candidate_email, 'event': event}
            return render(request, 'events/registration_complete.html', context)
        else:
            return render(request, 'events/detail.html', {'event': event, 'form': form})

    else:  # if a GET (or any other method) we'll create a blank form
        form = RegisterForm()
        form.fields['candidate_job_postings'].choices = get_job_postings_for_event(event_id)
        return render(request, 'events/detail.html', {'event': event, 'form': form})

    return render(request, 'events/detail.html', {'event': event, 'form': form})


def edit(request, event_id):
    if event_id:
        event = get_object_or_404(Event, pk=event_id)
    else:
        event = False

    if request.method == 'POST':  # if this is a POST request we need to process the form data
        form = EventForm(request.POST)
        form.fields['event_jobs'].choices = get_all_enabled_job_postings()
        form.fields['event_default_template'].choices = get_all_enabled_email_templates()
        if form.is_valid():
            update_or_create_event(request, form, event_id)
            response = {'status': 301, 'location': '/events/'}
            return HttpResponse(json.dumps(response), content_type='application/json')
        else:
            return render(request, 'events/evt_modal.html', {'event': event, 'form': form})

    else:  # if a GET (or any other method) we'll create a blank form
        form = EventForm()
        if event:
            form.fields['event_date'].initial = event.date_time
            form.fields['event_title'].initial = event.title
            form.fields['event_jobs'].choices = get_all_enabled_job_postings()
            form.fields['event_jobs'].initial = get_job_posting_ids_for_event(event_id)
            form.fields['event_auto_send'].initial = event.auto_email
            form.fields['event_sender'].initial = event.auto_email_from
            form.fields['event_default_template'].choices = get_all_enabled_email_templates()

            if event.email_template is not None:
                form.fields['event_default_template'].initial = event.email_template.id

            print (get_job_posting_ids_for_event(event_id))
        else:
            form.fields['event_jobs'].choices = get_all_enabled_job_postings()
            form.fields['event_default_template'].choices = get_all_enabled_email_templates()

        return render(request, 'events/evt_modal.html', {'event': event, 'form': form})


def get_job_postings_for_event(event_id):
    return [(job_posting.id, str(job_posting)) for job_posting in JobPosting.objects.filter(enabled=True).filter(event__id=event_id)]

def get_job_posting_ids_for_event(event_id):
    return [job_posting.id for job_posting in JobPosting.objects.filter(enabled=True).filter(event__id=event_id)]

def get_all_enabled_job_postings():
    return [(job_posting.id, str(job_posting)) for job_posting in JobPosting.objects.filter(enabled=True)]

def get_all_enabled_email_templates():
    return [('','')] + [(email_template.id, str(email_template)) for email_template in EmailTemplate.objects.filter(enabled=True)]

def update_or_create_candidate(request, form, event_id):
    f_email = form.cleaned_data['candidate_email']
    f_first_name = form.cleaned_data['candidate_first_name']
    f_last_name = form.cleaned_data['candidate_last_name']
    f_phone = form.cleaned_data['candidate_phone']
    job_posting_ids = request.POST.getlist('candidate_job_postings')
    f_selected_job_postings = []
    for job_id in job_posting_ids:
        f_selected_job_postings += [JobPosting.objects.get(id=job_id)]
    event_attended = Event.objects.get(id=event_id)
    person = Candidate.objects.filter(email=f_email).first()

    if person is None:
        person = Candidate(first_name=f_first_name, last_name=f_last_name, email=f_email, phone=f_phone)
    else:
        person.first_name = f_first_name
        person.last_name = f_last_name
        person.phone = f_phone

    person.save()

    attendance_list = []
    for job_posting in f_selected_job_postings:
        attendance = Attendance.objects\
            .filter(candidate=person)\
            .filter(event=event_attended)\
            .filter(selected_job_posting=job_posting)\
            .first()
        if attendance is None:
            attendance = Attendance(candidate=person, event=event_attended, selected_job_posting=job_posting)
            attendance.save()
        attendance_list += [attendance]

    # Send emails automatically when the event creator wants them
    if event_attended.auto_email and event_attended.auto_email_from and event_attended.email_template:
        send_emails(request, event_attended.email_template, attendance_list, event_attended,
                    from_email=event_attended.auto_email_from)

    return f_email

def update_or_create_event(request, form, event_id):
    print(event_id)
    f_date = form.cleaned_data['event_date']
    f_title = form.cleaned_data['event_title']
    f_auto = form.cleaned_data['event_auto_send']
    f_sender = form.cleaned_data['event_sender']
    template_id = request.POST.get('event_default_template')
    if template_id != '':
        f_template = EmailTemplate.objects.get(id=request.POST.get('event_default_template'))
    else:
        f_template = None
    job_posting_ids = request.POST.getlist('event_jobs')
    if event_id is None:
        event = Event(title=f_title, date_time=f_date, enabled=True, auto_email=f_auto, auto_email_from=f_sender, email_template=f_template)
        event.save()
        event.job_postings=job_posting_ids
    else:
        event = Event.objects.get(id=event_id)
        event.title = f_title
        event.date_time = f_date
        event.job_postings = job_posting_ids
        event.auto_email = f_auto
        event.auto_email_from = f_sender
        event.email_template = f_template

    event.save()
    return

events/templates/events/detail.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}Register{% endblock %}

{% block content %}

{% load static %}

<div class="row starter-template">
  <div class="centerContainer">
    <div class="col-sm-12 center wide-top">
      <img alt='top design' class="BannerImg" src='{% static "events/img/banner.png" %}'/>
  </div>
    <div class="row">
      <div class='eventTitle row'>{{ event.title }}</div>
      <div class='eventDate row'>{{ event.date_time }}</div>
    </div>
    <div class="spacer"></div>
    <form action="/events/{{ event.id }}/" id="id-registrationForm" method="post">
            {% csrf_token %}
            <div class="ta-left form-group required">
                <div>{{ form.candidate_first_name|add_label_class:"input-Labels" }}</div>
                <div>{{ form.candidate_first_name|add_class:"input" }}</div>
            </div>

            <div class="ta-left form-group required">
                <div>{{ form.candidate_last_name|add_label_class:"input-Labels" }}</div>
                <div>{{ form.candidate_last_name|add_class:"input" }}</div>
            </div>

            <div class="ta-left form-group required">
                <div>{{ form.candidate_email|add_label_class:"input-Labels" }}</div>
                <div>{{ form.candidate_email|add_class:"input" }}</div>
                {% if form.candidate_email.errors %}
                  <p class="alert alert-danger"> {{ form.candidate_email.errors.as_text }} </p>
                {% endif %}
            </div>

            <div class="ta-left form-group">
                <div>{{ form.candidate_phone|add_label_class:"input-Labels" }}</div>
                <div id="candidate_phone">{{ form.candidate_phone|add_class:"input" }}</div>
                {% if form.candidate_phone.errors %}
                  <p class="alert alert-danger"> {{ form.candidate_phone.errors.as_text }} </p>
                {% endif %}
            </div>

            <div class="ta-left form-group required">
                <div>{{ form.candidate_job_postings|add_label_class:"input-Labels" }}</div>
                <div class="input-Multi">{{ form.candidate_job_postings }}</div>
                {% if form.candidate_job_postings.errors %}
                  <p class="alert alert-danger"> {{ form.candidate_job_postings.errors.as_text }} </p>
                {% endif %}
            </div>

             <div class="form-group button-group">
                <button class="btn btn-lg btn-secondary" type="reset" id="reset-form">Clear</button>
                <button class="btn btn-lg btn-primary" type="submit" id="submit-form" disabled>Submit</button>
            </div>
        </form>
    </div>
</div>

<script src='{% static "events/js/bootstrap-multiselect.js" %}'></script>

<script>
  $(document).ready(function() {
    var validate_form = function(){
      var good = true;

      $('.required input:not([type="checkbox"])').each(function(i){
        if($(this).val() == '') good = false;
      });

      if(good && $('.required input[type="checkbox"]:checked').length > 0){
          $('#submit-form').attr('disabled', false);
      }
      else {
        $('#submit-form').attr('disabled', true);
      }
    };

    $('#candidate_phone').keyup(function(evt) {
      var input_phone = $('#candidate_phone input').val();
      var phone = input_phone;
      //Replace copy/paste, etc. characters so we end up with NNN-NNN-NNNN
      phone = phone.replace('+1',''); // International notation (from autofill); rejects foreign numbers
      phone = phone.replace('(','');
      phone = phone.replace(')','');
      phone = phone.replace('--',''); // People typing in (NNN)NNN-NNNN without looking will end up with NNN-NNN--NNNN ... so fix it here
      phone = phone.replace(/\./g,'');
      phone = phone.replace(/\s/g,'');

      var len = phone.length;

      //add dashes after enty of 3rd and 6th digits \
      if(len == 3 || len == 7){
        //If the keyup was a backspace, get rid of the previous number as well.
        if(evt.which != 8) {
          phone += '-';
        }
        else {
          phone = phone.substring(0, phone.length - 1);
        }
      }
      else if(len == 10){
        var regex = /[0-9]{10}/;
        var found = phone.match(regex);
        if(found) { // Must have pasted it in.... reformat
          phone = phone.substring(0,3) + '-' + phone.substring(3,6) + '-' + phone.substring(6);
        }
      }
      else if(len == 11){ // check for stripped parens, but still a dash.  i.e pasted (NNN) NNN-NNNN
        var regex = /[0-9]{6}-[0-9]{4}/;
        var found = phone.match(regex);
        if(found) {
          phone = phone.substring(0,3) + '-' + phone.substring(3);
        }
      }
      if(phone != input_phone) $('#candidate_phone input').val(phone);
    });

    $('#id_candidate_job_postings').multiselect();

    $('.required input').change(validate_form);

    //Multi-select doesn't refresh properly from click.
    $('#reset-form').click(function(evt){
      // Let the actual event happen first, then do stuff.  Change event is not
      // triggered from form reset so do that too.
      setTimeout(function(){
        $('#id_candidate_job_postings').multiselect('refresh');
        validate_form();
      }, 50);
    });
  });
</script>

{% endblock %}

events/templates/events/et_index.html
{% extends "base.html" %}
{% load static %}

{% block title %} Excella Recruiting {% endblock %}

{% block header %}
    {% include "banner/banner.html" with nav_tmpl="banner/banner_large.html" title="Email Templates"%}
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

  <div class="add-item" data-toggle="modal" data-target="#addTemplate" data-placement="left" title="Add New Template"></div>
{% else %}
  <br />
  <br />
{% endif %}
<div class="starter-template">

  {% if has_templates %}
    <div class="row">
        <div class="col-md-1 ta-left"><h4>ID</h4></div>
        <div class="col-md-3 ta-left"><h4>Subject</h4></div>
        <div class="col-md-5"></div>
    </div>
    {% for template in email_template_list %}
      <div class="row list-item {% if not template.enabled %}disabled{% endif %}">
        <div class="col-md-1 ta-left">{{ template.id }}</div>
        <div class='col-md-3 ta-left'>{{ template.subject }}</div>

          <div class='col-md-3 ta-right'>
            {% if user.is_authenticated %}
              {% if user.is_superuser %}
                <button data-template-id="{{ template.id }}" class="btn btn-link edit-template" title="Edit/View template">Edit</button>
              {% endif %}
            {% endif %}
          </div>
      </div>
    {% endfor %}
  {% else %}
    <div class="centerContainer">
      <img src="/static/excellajobs/images/oops.svg"/>
      <h4>Oooooppss!!</h4>
      <div style="width: 50%; margin: 0 25%;">
        <div>Looks like your template list is empty. Add a template by clicking <i class="fa fa-plus-circle" style="font-size:1.6em; color:#3366BB"></i> button above and let’s begin!</div>
      </div>
    </div>
  {% endif %}
  {% if user.is_authenticated %}
    <div class="modal fade modal-full-screen" id="addTemplate" tabindex="-1" role="modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"></h4>
          </div>
          <iframe id="et-frame" class="modal-iframe" src="./templates/edit/"></iframe>
        </div>
      </div>
    </div>
  {% endif %}
</div>

<script type="text/javascript">
  $(function () {
    $('.add-item').tooltip();

    $('.add-item').click(function(){
      $('.modal-title').html('CREATE NEW TEMPLATE');
      $('#et-frame').attr('src', "./templates/edit/")
      // $.ajax({
      //   url: "./templates/edit/"
      // }).done(function(data) {
      //   $( '#addTemplate .modal-body' ).replaceWith( data );
      // });
    });

    $('.edit-template').click(function(){
      $('.modal-title').html('EDIT TEMPLATE');

      $('#et-frame').attr('src', "./templates/edit/" + $(this).data('template-id'));
      $( '#addTemplate').modal('show');
      // $.ajax({
      //   url: "./templates/edit/" + $(this).data('template-id')
      // }).done(function(data) {
      //   $( '#addTemplate .modal-body' ).replaceWith( data );
      //   $( '#addTemplate').modal('show');
      // });
    });

    $('body').addClass('greybg');  // Not ideal, but would need to re-do the base template otherwise
  });

  function formComplete(){
    location.reload();
  }
</script>
{% endblock %}

events/templates/events/et_modal.html
{% load static %}
{% load widget_tweaks %}
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Custom local static styles for this template -->
    <link href="{% static "events/css/starter-template.css" %}" rel="stylesheet">
    <link href="{% static "events/css/modals.css" %}" rel="stylesheet">
    <link href="{% static "events/css/bootstrap-multiselect.css" %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- CDN's for Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <script type="text/javascript" src="/static/tiny_mce/tiny_mce.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="/static/django_tinymce/init_tinymce.js"></script>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/blitzer/jquery-ui.css"/>
    <title>{% block title %} {% endblock %}</title>
  </head>


  <body class="starter-template">
      <div class="modal-body">
        <div class="row"><h2 class="tight-top">Edit Template</h2></div>
        <div class="container">
          <form action="/events/templates/edit/{{ email_template.id }}/" id="id-templateForm" method="post">
            {% csrf_token %}
            <div class="form-group required ta-left" id="email-template">
                <div>
                  {{ form.subject|add_label_class:"input-Labels" }}
                  {{ form.subject|add_class:"input" }}
                </div>
            </div>
            <div class="form-group required ta-left" id="email-template">
                <div>
                  <p>
                    {{ form.body|add_label_class:"input-Labels" }} {As HTML}
                  </p>
                  <br />
                  {{ form.body|add_class:"form-control"|safe }}
                </div>
            </div>
            <div class="form-group required ta-left" id="email-template">
                <div>
                  {{ form.enabled|add_label_class:"input-Labels" }}
                  {{ form.enabled|add_class:"input-checkbox" }}
                </div>
            </div>
            <div class="form-group">
               <div class="center">
                 <button class="btn btn-primary btn-lg" id="template_submit"
                   type="submit"
                   style="min-width: 16em;">Save</button>
               </div>
             </div>
          </form>
        </div>
        {{ form.non_field_errors }}
      </div>


  </body>
</html>

events/templates/events/evt_modal.html
{% load widget_tweaks %}

{% block content %}

      <div class="modal-body">
        <div class="row"><h2 class="tight-top">Enter Event</h2></div>
        <div class="container">

          <form action="/events/edit/{{ event.id }}/" id="id-registrationForm" method="post">
                  {% csrf_token %}
                  <div class="form-group required ta-left">
                      <div>{{ form.event_date|add_label_class:"input-Labels" }}</div>
                      <div>{{ form.event_date|add_class:"input" }}</div>
                  </div>

                  <div class="form-group required ta-left">
                      <div>{{ form.event_title|add_label_class:"input-Labels" }}</div>
                      <div>{{ form.event_title|add_class:"input" }}</div>
                  </div>

                  <div class="form-group required ta-left">
                      <div>{{ form.event_jobs|add_label_class:"input-Labels" }}</div>
                      <div class="input-Multi">{{ form.event_jobs }}</div>
                      {% if form.event_jobs.errors %}
                        <p class="alert alert-danger"> {{ form.event_jobs.errors.as_text }} </p>
                      {% endif %}
                  </div>

                  <div class="form-group ta-left" style="margin-bottom: 0;">
                      <div>{{ form.event_auto_send|add_label_class:"input-Labels" }}{{ form.event_auto_send|add_class:"input-checkbox" }}</div>
                  </div>
                  <div class="form-group required ta-left" id="email-sender">
                      <div>{{ form.event_sender|add_label_class:"input-Labels" }}</div>
                      <div>{{ form.event_sender|add_class:"input" }}</div>
                      {% if form.event_sender.errors %}
                        <p class="alert alert-danger"> {{ form.event_sender.errors.as_text }} </p>
                      {% endif %}
                  </div>
                  <div class="form-group required ta-left" id="email-template">
                      <div>{{ form.event_default_template|add_label_class:"input-Labels" }}</div>
                      <div>{{ form.event_default_template|add_class:"input" }}</div>
                      {% if form.event_default_template.errors %}
                        <p class="alert alert-danger"> {{ form.event_default_template.errors.as_text }} </p>
                      {% endif %}
                  </div>
                   <div class="form-group">
                      <div class="center">
                        <button class="btn btn-primary btn-lg" id="event_submit"
                          type="submit" disabled
                          style="min-width: 16em;">Save</button>
                      </div>
                  </div>
              </form>
        </div>
        {{ form.non_field_errors }}
      </div>

    <script>
      $(function () {
        var date = moment($('#id_event_date').val()).toDate();
        $('#id_event_date').datepicker({dateFormat: 'yy-mm-dd', defaultDate: date});
        $('#id_event_jobs').multiselect();

        $('#event_submit').click(function(evt){
          evt.preventDefault();

          $.post("/events/edit/{{ event.id }}/",
            $( "#id-registrationForm" ).serialize(),
            function(data) {
              if(data.status && data.status == 301) window.location.href = data.location;
              else $( '#addEvent .modal-body' ).replaceWith(data);
            });
        });

        /* Ensure all required fields have values.  If so, enable save button */
        var checkInput = function() {
          var good = true;

          if($('#id_event_auto_send').is(':checked')){
            $('#email-sender, #email-template').addClass('required');
            $('#email-sender input, #email-sender label').removeAttr('disabled');
          }
          else{
            $('#email-sender, #email-template').removeClass('required');
            $('#email-sender input, #email-sender label').attr('disabled', true);
          }

          $('.required input:not([type="checkbox"][disabled]), .required select').each(function(i){
            if($(this).val() == '') good = false;
          });



          if(good && $('.required input[type="checkbox"]:checked').length > 0){
            $('#event_submit').attr('disabled', false);
          }
          else {
            $('#event_submit').attr('disabled', true);
          }
        } // checkInpui

        $('.required input, .required select, #id_event_auto_send').change(function(evt){
          checkInput();
        });

        checkInput();
      });
    </script>
{% endblock %}