events/urls.py
from django.conf.urls import url

from . import views
from . import email_template_views
from . import job_posting_views

app_name = 'events'

urlpatterns = [
    url(r'^(?P<event_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^edit/(?P<event_id>[0-9]+)?/?$', views.edit, name='edit'),
    url(r'^templates/edit/(?P<template_id>[0-9]+)?/?$', email_template_views.edit, name='edit_email_template'),
    url(r'^templates$', email_template_views.index, name='email_template_index'),
    url(r'^postings/edit/(?P<job_posting_id>[0-9]+)?/?$', job_posting_views.edit, name='job_posting_template'),
    url(r'^postings$', job_posting_views.index, name='job_posting_template'),
    url(r'^$', views.index, name='index'),
]

sendemail/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'sendemail'

urlpatterns = [
    url(r'^(?P<event_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<event_id>[0-9]+)/export$', views.exportXlsx, name='exportXlsx'),
    url(r'^$', views.index, name='index'),
]

sendemail/models/email_log.py
from __future__ import unicode_literals
from django.db import models
from tinymce.models import HTMLField

from events.models.candidate import Candidate
from events.models.event import Event


class EmailLog(models.Model):
    event_id = models.ForeignKey(Event)
    candidate_id = models.ForeignKey(Candidate)
    to_address = models.CharField('To', max_length=200)
    cc_address = models.CharField('CC', max_length=200, blank=True, null=True)
    bcc_address = models.CharField('BCC', max_length=200, blank=True, null=True)
    from_address = models.CharField('From', max_length=200)
    subject = models.CharField('Subject', max_length=100)
    time_sent = models.DateTimeField(auto_now=True)
    body = HTMLField()
    response = models.TextField(editable=False, blank=True, null=True)

sendemail/models/email_template.py
from django.db import models
from tinymce.models import HTMLField


class EmailTemplate(models.Model):
    subject = models.CharField('Subject', max_length=100)
    body = HTMLField()
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return "{0} - {1}".format(self.id, self.subject)

    class Meta:
        ordering = ['id', 'subject']

sendemail/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset
from django import forms

from sendemail.models.email_template import EmailTemplate


class SendEmailForm(forms.Form):
    error_css_class = 'errorlist'

    email_templates = forms.ChoiceField(label='Email Template', initial='', required=True)

    class Meta:
        model = EmailTemplate

    def __init__(self, *args, **kwargs):
        super(SendEmailForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(form=self)
        self.helper.form_id = 'id-registrationForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-10'
        self.helper.form_method = 'post'
        self.helper.form_action = 'detail'
        self.helper.layout = Layout(
            Fieldset(
                'Choose Email Template',
                'email_templates',
            ),
        )

sendemail/views.py
import os
from collections import defaultdict

import sendgrid
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from sendgrid.helpers.mail import *

from sendemail.forms import SendEmailForm
from sendemail.xlsx_formatter import *
from sendemail.models.email_log import EmailLog
from sendemail.models.email_template import EmailTemplate
from events.models.attendance import Attendance
from events.models.event import Event


@login_required
def exportXlsx(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    file_name = "Attendee_List_Event_{0}.xlsx".format(event.id)
    response = HttpResponse(content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename={0}'.format(file_name)

    attendance_list = Attendance.objects.filter(event=event)
    xlsx_data = writeToExcel(attendance_list, event)
    response.write(xlsx_data)
    return response


@login_required
def index(request):
    event_list = Event.objects.filter(enabled=True).order_by('-date_time')
    context = {'event_list': event_list}
    return render(request, 'sendemail/index.html', context)


@login_required
def detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    attendance_detail = Attendance.candidates_for_event(event_id)
    attendance_count = len(attendance_detail) #Attendance.objects.values_list('candidate').filter(event=event).distinct().count()
    no_email = request.user.email is None or request.user.email == '';

    if request.method == 'POST':  # if this is a POST request we need to process the form data
        form = SendEmailForm(request.POST)
        form.fields['email_templates'].choices = get_all_active_email_templates()
        if form.is_valid():
            email_template_id = request.POST.getlist('email_templates')[0]
            email_template = EmailTemplate.objects.get(id=email_template_id)
            attendance_list = Attendance.objects.filter(event=event)
            error_emails = send_emails(request, email_template, attendance_list, event)
            if len(error_emails):
                for attendance in attendance_detail:
                    if attendance.email in error_emails:
                        attendance.email_error = True
    else:  # if a GET (or any other method) we'll create a blank form
        form = SendEmailForm()
        form.fields['email_templates'].choices = get_all_active_email_templates()
        error_emails = None
        if event.email_template:
            form.initial['email_templates'] = event.email_template.id

    return render(request, 'sendemail/detail.html', {'event': event,
                                                 'no_email': no_email,
                                                 'user_id' : request.user.id,
                                                 'attendance_list': attendance_detail,
                                                 'bad_emails': error_emails,
                                                 'attendance_count': attendance_count,
                                                 'form': form})


def get_all_active_email_templates():
    templates = [(email_template.id, str(email_template)) for email_template in
                 EmailTemplate.objects.filter(enabled=True)]
    templates.insert(0, ('', ''))
    return templates


def send_emails(request, email_template, attendance_list, event, from_email=None):
    if not from_email:
        from_email = str(request.user.email)

    email_recipients = defaultdict(list)
    for attendance in attendance_list:
        email_recipients[attendance.candidate] += [attendance.selected_job_posting]

    email_errors = [];

    for candidate, job_postings in email_recipients.items():
        to_email = str(candidate.email)
        subject = str(email_template.subject)
        email_body = email_template.body.replace('##FIRST_NAME##', candidate.first_name)
        email_body = email_body.replace('##LAST_NAME##', candidate.last_name)
        email_body = email_body.replace('##EVENT##', event.title)

        job_names = []
        job_list = []
        job_posting = []
        for posting in job_postings:
            job_names += ['<a href="{link}">{name}</a>' \
                .format(name=posting.title, link=posting.job_link)]
            job_list += ['<li><a href="{link}">{name}</a></li>' \
                .format(name=posting.title, link=posting.job_link)]
            job_posting += ['<a href="{link}">{link}</a>'.format(link=posting.job_link)]

        job_names = format_list_string(job_names, separator_2_items=' or ', last_separator=', or ')
        job_list = format_list_string(job_list, prefix='<ul>', separator='', postfix='</ul>')
        job_posting = format_list_string(job_posting, separator_2_items=' and ', last_separator=', and ')

        email_body = email_body.replace('##JOB_NAMES##', job_names)
        email_body = email_body.replace('##JOBS_LIST##', job_list)
        email_body = email_body.replace('##JOBPOSTING##', job_posting)  # legacy

        response = send_email(event, candidate, from_email, to_email, subject, str(email_body))
        if response != 'SENT':
            email_errors.append(to_email)

    return email_errors

# Creates grammatically correct lists with and/or/but in English, no matter which comma rule is used
def format_list_string(list_items, prefix='', separator=', ', separator_2_items=None, last_separator=None, postfix=''):
    if not separator_2_items:
        separator_2_items = separator
    if not last_separator:
        last_separator = separator
    result = prefix
    if len(list_items) <= 1:
        result += separator.join(list_items[0:])
    elif len(list_items) <= 2:
        result += separator_2_items.join(list_items)
    else:
        result += separator.join(list_items[0:-1]) + last_separator + list_items[-1]
    result += postfix
    return result


def send_email(event, candidate, from_address, to_address, subject, body_text):
    sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
    from_email = Email(from_address)
    to_email = Email(to_address)

    content = Content(type_='text/html', value=body_text)
    current_email = Mail(from_email, subject, to_email, content)
    print('#############################')
    print('Send Email {0} : {1}'.format(to_address, subject))
    print('#############################')
    try:
        if os.environ.get('SENDGRID_API_KEY'):
            response = sg.client.mail.send.post(request_body=current_email.get())
        else:
            if(to_address == 'test@bad.net'):
                response = send_mail(subject, body_text, from_address, [])
            else:
                response = send_mail(subject, body_text, from_address, [to_address])

    except Exception as err:
        response = 'Failed to send Email: ', err

    if response == 1 or (not isinstance(response, (int, str)) and response.status_code == 202):
        response = 'SENT'

    EmailLog(event_id=event,
             candidate_id=candidate,
             to_address=to_address,
             from_address=from_address,
             subject=subject,
             body=body_text,
             response=response).save()
    return response

sendemail/templates/sendemail/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% crispy sendemail_form sendemail_form.helper %}

{% block header %}
    {% include "banner/banner.html" with nav_tmpl="banner/banner_large.html" title=event%}
{% endblock %}

{% block content %}

<br />
<div class="starter-template">
<div class='row'>
    <div class='col-xs-6 ta-left'><a href="{{ request.META.HTTP_REFERER }}">< back</a></div>
    <div class='col-xs-6 ta-right'>{{ event.date_time }}</div>
</div>

{% if attendance_list %}
<div class="row">
  <div class='col-md-12'>
      <form action="/sendemail/{{ event.id }}/" name="id-registrationForm" id="id-registrationForm" method="post">
          {% csrf_token %}
          {% crispy form form.helper %}

          {% if no_email %}
            <div class="alert alert-warning" role="alert">
              You have no email set in your user profile.  Cannot send emails
              without it.  Please update your user profile and add a valid email address.
              <a href="/admin/auth/user/{{user_id}}/change/">Edit Profile</a>
            </div>
          {% endif %}
          <!-- Button trigger modal -->
          <div class="container col-md-12">
              <div class="row-fluid">
                  <button id="id-send-email-button" type="button" class="btn btn-primary btn-lg pull-left"
                        data-toggle="modal" data-target="#myModal">Send Emails</button>
                  <a href="/sendemail/{{ event.id }}/export" class="btn btn-primary btn-lg pull-right" role="button">Export XLSX</a>
              </div>
          </div>

          <!-- Modal -->
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel">Send Emails!</h4>
                </div>
                <div class="modal-body">
                    <p>You are about to send emails to the selected individuals.</p>
                    <p>Are you sure?</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                  <button type="button" class="btn btn-primary" onClick="submitEmailForm();">Send</button>
                </div>
              </div>
            </div>
          </div>
      </form>
  </div>
</div>

<div class='row'>
  <div class='col-xs-12'>
    <div class="row">
        <div class="col-xs-12 ta-left"><h3>Applicants</h3></div>
    </div>
    <br />
    <div class="row center">
        <div class='col-lg-1'><h4>Selected</h4></div>
        <div class='col-lg-2'><h4>First Name</h4></div>
        <div class='col-lg-2'><h4>Last Name</h4></div>
        <div class='col-lg-2'><h4>Phone Number</h4></div>
        <div class='col-lg-2'><h4>Email Address</h4></div>
        <div class='col-lg-3'><h4>Job</h4></div>
    </div>
  </div>
</div>
{% endif %}

    {% for attendance in attendance_list %}
      <div class="row center list-item {% if attendance.email_error %}error{% endif %}"
        {% if attendance.email_error %}data-toggle="tooltip" data-placement="right" title="Error sending email.  Please see email log for additional details."{% endif %}>
        <div class='col-lg-1'><input id="students" type="checkbox"></div>
        <div class='col-lg-2'>{{ attendance.first_name }}</div>
        <div class='col-lg-2'>{{ attendance.last_name }}</div>
        <div class='col-lg-2'>{{ attendance.phone }}</div>
        <div class='col-lg-2' title="{{ attendance.email }}">{{ attendance.email|truncatechars:"45" }}</div>
        <div class='col-lg-3'>{{ attendance.postings }}</div>
      </div>
    {% empty %}
      <div class="centerContainer">
        <img src="/static/excellajobs/images/oops.svg"/>
        <h4>No applicants!!</h4>
        <div style="width: 50%; margin: 0 25%;">
          <div>You do not have any applicant submissions for this event at this time.</div>
        </div>
      </div>
    {% endfor %}
</div>

<script type="text/javascript">
    function submitEmailForm() {
        alert(JSON.stringify($('#students')));
       // HTMLFormElement.prototype.submit.call($('#id-registrationForm')[0]);
    }

    $(document).ready(function() {
      var no_email = eval("{{ no_email }}".toLowerCase());

      if ($("#id_email_templates").val() == "" || no_email) {
        $('#id-send-email-button').attr('disabled', 'true')
      }

      $(document).on('change','#id_email_templates',function(){
        console.log(no_email)
        if ($('#id_email_templates').val() != "" && !no_email) $('#id-send-email-button').removeAttr('disabled');
        else $('#id-send-email-button').attr('disabled', 'true');
      });

      $('body').addClass('greybg');
    });
</script>
{% endblock %}

sendemail/templates/sendemail/index.html
{% extends "base.html" %}

{% block title %} Exelaration Recruiting {% endblock %}

{% block header %}
    {% include "banner/banner.html" with nav_tmpl="banner/banner_large.html" title="Send Emails"%}
{% endblock %}

{% block content %}
<div class="starter-template">
  <h1>Which Event would you like to send email for?</h1>
  <hr />
  {% for event in event_list %}
      <div class='col-md-12'>
        <div class='col-md-2'>{{ event.date_time }}</div>
        <div class='col-md-6'><a href="{{ event.id }}/">{{ event.title }}</a></div>
      </div>
  {% endfor %}
</div>
{% endblock %}